### ISSUE TITLE
detecting blocking call

### ISSUE THREAD

**Issue by kylelutze** [explosivo22/rinnaicontrolr-ha#84] opened 2024-09-17 11:18 UTC
I'm getting 3 errors in the log and the integration fails to load
```
Logger: homeassistant.util.loop
Source: util/loop.py:136

Detected blocking call to import_module with args ('custom_components.rinnai.device_action',) 
inside the event loop by integration 'device_automation' at homeassistant/components/device_automation/__init__.py,
line 172: platform = await integration.async_get_platform(platform_name) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), 
please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+device_automation%22 
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module 
Traceback (most recent call last): 
File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code 
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) 
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) 
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() 
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) 
File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", 
line 217, in _async_get_device_automations_from_domain platform = await async_get_device_automation_platform( File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", 
line 172, in async_get_device_automation_platform platform = await integration.async_get_platform(platform_name)
```

```
Logger: homeassistant.setup
Source: setup.py:334

Setup failed for custom integration 'rinnai': Unable to import component: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.12/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.12/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/session.py", line 12, in <module>
    from .client import AioBaseClient, AioClientCreator
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.client import (
ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.12/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.12/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/session.py", line 12, in <module>
    from .client import AioBaseClient, AioClientCreator
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.client import (
ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)
```

```
Logger: homeassistant.util.loop
Source: util/loop.py:77

Detected blocking call to import_module with args ('custom_components.rinnai',) 
in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; 
This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue 
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module 
Traceback (most recent call last): File "<frozen runpy>", 
line 198, in _run_module_as_main File "<frozen runpy>", 
line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", 
line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", 
line 209, in main exit_code = runner.run(runtime_conf) 
File "/usr/src/homeassistant/homeassistant/runner.py", 
line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() 
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() 
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) 
File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) 
File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() 
File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() 
File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

**Comment by rr326** [comment] 2024-10-11 15:59
I just fixed that in one of my components and is is pretty easy. This is what worked for me:

Within an async function, change:
```
filecontent = SCRIPT_PATH.read_text(encoding="utf-8", errors="ignore")
```

to
```
import asyncio # Put this at the top of the module

loop = asyncio.get_running_loop()
filecontent = await loop.run_in_executor(
    None, lambda: SCRIPT_PATH.read_text(encoding="utf-8", errors="ignore")
    )
```

**Comment by explosivo22** [comment] 2024-10-25 03:26
Duplicate of #81

**Closed** 2024-10-25 03:26 UTC
