### ISSUE TITLE
Detected blocking call to listdir

### ISSUE THREAD

**Issue by matt1131** [explosivo22/rinnaicontrolr-ha#82] opened 2024-08-19 04:48 UTC
Looks like this is happening in 1.4.3

Core 2024.7.4
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240710.0

```

Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 306: for d in os.listdir(possible_path)), please report it to the author of the 'rinnai' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(
Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/robomaker',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 311: api_versions = os.listdir(full_dirname)), please report it to the author of the 'rinnai' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(
Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/cognito-idp',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 363: for dirname in os.listdir(possible_path):), please report it to the author of the 'rinnai' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(
```

**Comment by philipflesher** [comment] 2024-09-15 16:31
This is an issue still.

**Comment by philipflesher** [comment] 2024-09-15 16:46
See also #83 -- probably should get fixed in tandem.

**Comment by philipflesher** [comment] 2024-10-06 15:24
This is still an issue AFAIK

**Comment by matt1131** [comment] 2024-10-07 03:03
yep, still seeing it

**Comment by matt1131** [comment] 2024-10-07 03:05
@explosivo22 are you around or available to look into this?

**Comment by explosivo22** [comment] 2024-10-07 03:12
I am around. I have been investigating when I get some down time. Testing things internally and hopeful I can get it fixed and pushed out.

**Comment by matt1131** [comment] 2024-10-07 03:15
wow, quick response! thanks, understand downtime can be hard to come by and appreciate you looking at this

**Comment by explosivo22** [comment] 2024-10-25 02:01
Going to roll this into one issue. Duplicate of #81

**Closed by explosivo22** 2024-10-25 02:01 UTC
Labels: bug, investigating
